# Generated by Django 5.1.2 on 2024-11-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_jobdescription_resume_interviewquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the user", max_length=100),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, help_text="Age of the user", null=True
                    ),
                ),
                ("goal", models.TextField(blank=True, help_text="User's career goals")),
                (
                    "bio",
                    models.TextField(blank=True, help_text="Short bio of the user"),
                ),
                (
                    "education",
                    models.TextField(blank=True, help_text="Education details"),
                ),
                (
                    "additional_info",
                    models.TextField(blank=True, help_text="Additional information"),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        help_text="Resume/CV upload",
                        null=True,
                        upload_to="resumes/",
                    ),
                ),
            ],
        ),
    ]
