# Generated by Django 5.1.2 on 2024-11-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_joblisting_is_favorite_userprofile_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joblisting",
            name="is_favorite",
        ),
    ]
