# Generated by Django 5.1.2 on 2024-11-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_jobdescription_user_joblisting_user_userprofile_user"),
        ("myapp", "0006_remove_joblisting_is_favorite"),
    ]

    operations = []
