# Generated by Django 5.1.1 on 2024-11-26 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_merge_20241125_2208"),
        ("myapp", "0008_alter_userprofile_user"),
    ]

    operations = []
