# Generated by Django 5.1.1 on 2024-12-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_merge_20241126_0047"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_saved",
            field=models.BooleanField(default=False),
        ),
    ]
